# Generated by Django 3.0.6 on 2020-05-12 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_restaurants'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restaurants',
            new_name='Restaurant',
        ),
    ]
